### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by 0verd0se** [Sanix-Darker/Brute-Force-Login#1]
python BFL.py
  File "BFL.py", line 9
    print "\n#####################################"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n#####################################")?
$ python BFL.py
  File "BFL.py", line 9
    print "\n#####################################"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\n#####################################")?

**Comment by prasathmani** [comment]
The print "statement" in Python 3.x is changed into ` print("statement")` and `raw_input` to `input`. so update your code to py 3.x

**Comment by fvillena** [comment]
The pull request #2 will solve this problem.

**Comment by Sanix-Darker** [comment]
Because the problem has been resolved, am closing this issue!
Thank's to @fvillena !
