### ISSUE TITLE
about csrf token

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [Sanix-Darker/Brute-Force-Login#12]
can you support csrf token? thx!!

(some csrf token is inside the `Cookie` ((just let u know if u dont know 😅

**Comment by Sanix-Darker** [comment]
Yeah, you mark a point, i will handle the csrf_token issue as soon as possible, but it's not a too big deal, just take the input hidden and ask BFL to read it's value before submit a login attempt !

**Comment by Sanix-Darker** [comment]
Hey @hahahahahahahahahahahahahahahah 

[csrf-token-handled](https://github.com/Sanix-Darker/Brute-Force-Login/commit/9878477cb6ffe59d14cc41d3d94bbaa5010d46ee)
