### ISSUE TITLE
Is there an intervals between each brute attack?

### ISSUE THREAD

**Issue by Mahassan313** [Sanix-Darker/Brute-Force-Login#13]
Hello there!
First of all thanks for you time 
Second "Is there any intervals between each brute attack?"
I mean the brute force stops every some seconds and starts again ...
This will make the bruteforcing somewhat save without any kind of captcha or account limit 
Third how many attack per time it provides?

**Comment by Sanix-Darker** [comment]
Actually no !
But you can add it using `time.sleep()` !

**Comment by Mahassan313** [comment]
Thanks
