### ISSUE TITLE
while trying to run i get this 

### ISSUE THREAD

**Issue by imavery** [Sanix-Darker/Brute-Force-Login#16]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\a\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-b0yeqxc_\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-b0yeqxc_\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\a\AppData\Local\Temp\pip-record-kz976ufv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\a\appdata\local\programs\python\python39\Include\lxml'
         cwd: C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\
    Complete output (84 lines):
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    c:\users\a\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\lxml
    copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\__init__.py -> build\lib.win-amd64-3.9\lxml
    creating build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.9\lxml\html
    creating build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
    copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
    creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    creating build\temp.win-amd64-3.9\Release\src\lxml
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\src\lxml\includes -Ic:\users\a\appdata\local\programs\python\python39\include -Ic:\users\a\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.9\Release\src\lxml\lxml.etree.obj -w
    cl : Command line warning D9025 : overriding '/W3' with '/w'
    lxml.etree.c
    C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
  Rolling back uninstall of lxml
  Moving to c:\users\a\appdata\local\programs\python\python39\lib\site-packages\lxml-4.6.1.dist-info\
   from C:\Users\a\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xml-4.6.1.dist-info
  Moving to c:\users\a\appdata\local\programs\python\python39\lib\site-packages\lxml\
   from C:\Users\a\AppData\Local\Programs\Python\Python39\Lib\site-packages\~xml
ERROR: Command errored out with exit status 1: 'c:\users\a\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-b0yeqxc_\\lxml\\setup.py'"'"'; __file__='"'"'C:\\Users\\a\\AppData\\Local\\Temp\\pip-install-b0yeqxc_\\lxml\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\a\AppData\Local\Temp\pip-record-kz976ufv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\a\appdata\local\programs\python\python39\Include\lxml' Check the logs for full command output.

**Comment by ndom91** [comment]
You have to install `libxml2-dev` and `libxslt1-dev` (package names on ubuntu)

**Comment by Sanix-Darker** [comment]
Did this worked for you ? @imavery

**Comment by nu11secur1ty** [comment]
Python 3.7 is a requirement, but 3.8 or the latest is recommended, Please use Linux distribution, for this software. And why you use visual studio :)
1. Try to install https://www.python.org/ftp/python/3.8.8/python-3.8.8rc1-embed-amd64.zip or the latest version of Python on your Windows without an external plugin editor, like VStudio or whatever, then try to run it again. And this output from your cmd is not talk anything about the problem!
2. So, please present this information `headers 'c:\users\a\appdata\local\programs\python\python39\Include\lxml' Check the logs for full command output.`
BR

**Comment by nu11secur1ty** [comment]
> ERROR: Command errored out with exit status 1:
> command: 'c:\users\a\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\setup.py'"'"'; **file**='"'"'C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\a\AppData\Local\Temp\pip-record-kz976ufv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\a\appdata\local\programs\python\python39\Include\lxml'
> cwd: C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml
> Complete output (84 lines):
> Building lxml version 3.4.4.
> Building without Cython.
> ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
> ** make sure the development packages of libxml2 and libxslt are installed **
> 
> ```
> Using build configuration of libxslt
> c:\users\a\appdata\local\programs\python\python39\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'bugtrack_url'
>   warnings.warn(msg)
> running install
> running build
> running build_py
> creating build
> creating build\lib.win-amd64-3.9
> creating build\lib.win-amd64-3.9\lxml
> copying src\lxml\builder.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\cssselect.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\doctestcompare.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\ElementInclude.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\pyclasslookup.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\sax.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\usedoctest.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\_elementpath.py -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\__init__.py -> build\lib.win-amd64-3.9\lxml
> creating build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\__init__.py -> build\lib.win-amd64-3.9\lxml\includes
> creating build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\builder.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\clean.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\defs.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\diff.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\ElementSoup.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\formfill.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\html5parser.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\soupparser.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\usedoctest.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\_diffcommand.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\_html5builder.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\_setmixin.py -> build\lib.win-amd64-3.9\lxml\html
> copying src\lxml\html\__init__.py -> build\lib.win-amd64-3.9\lxml\html
> creating build\lib.win-amd64-3.9\lxml\isoschematron
> copying src\lxml\isoschematron\__init__.py -> build\lib.win-amd64-3.9\lxml\isoschematron
> copying src\lxml\lxml.etree.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\lxml.etree_api.h -> build\lib.win-amd64-3.9\lxml
> copying src\lxml\includes\c14n.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\config.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\dtdvalid.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\etreepublic.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\htmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\relaxng.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\schematron.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\tree.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\uri.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xinclude.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlerror.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlparser.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xmlschema.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xpath.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\xslt.pxd -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\etree_defs.h -> build\lib.win-amd64-3.9\lxml\includes
> copying src\lxml\includes\lxml-version.h -> build\lib.win-amd64-3.9\lxml\includes
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
> copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\rng
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl
> creating build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win-amd64-3.9\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
> running build_ext
> building 'lxml.etree' extension
> creating build\temp.win-amd64-3.9
> creating build\temp.win-amd64-3.9\Release
> creating build\temp.win-amd64-3.9\Release\src
> creating build\temp.win-amd64-3.9\Release\src\lxml
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\src\lxml\includes -Ic:\users\a\appdata\local\programs\python\python39\include -Ic:\users\a\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc\lxml\lxml.etree.c /Fobuild\temp.win-amd64-3.9\Release\src\lxml\lxml.etree.obj -w
> cl : Command line warning D9025 : overriding '/W3' with '/w'
> lxml.etree.c
> C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\src\lxml\includes\etree_defs.h(14): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
> ----------------------------------------
> ```
> 
> Rolling back uninstall of lxml
> Moving to c:\users\a\appdata\local\programs\python\python39\lib\site-packages\lxml-4.6.1.dist-info
> from C:\Users\a\AppData\Local\Programs\Python\Python39\Lib\site-packages~xml-4.6.1.dist-info
> Moving to c:\users\a\appdata\local\programs\python\python39\lib\site-packages\lxml
> from C:\Users\a\AppData\Local\Programs\Python\Python39\Lib\site-packages~xml
> ERROR: Command errored out with exit status 1: 'c:\users\a\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\setup.py'"'"'; **file**='"'"'C:\Users\a\AppData\Local\Temp\pip-install-b0yeqxc_\lxml\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\a\AppData\Local\Temp\pip-record-kz976ufv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\a\appdata\local\programs\python\python39\Include\lxml' Check the logs for full command output.

Is everything ok, my friend? :) Please answer the question, because now there is no problem with the software! If you don't want to answer, we will be closed the case anyway! This case is open for a long time! BR
