### ISSUE TITLE
Supported Python Versions?

### ISSUE THREAD

**Issue by ndom91** [Sanix-Darker/Brute-Force-Login#17]
Trying to install the requirements, has to build lxml and errors out with a bunch of "`exc_typ` - did you mean `curexc_type`?" I've installed all the xml related prerequisites.

I'm runnign python 3.8.5. 

Does this need to run under an older version?

**Comment by Sanix-Darker** [comment]
Hey @ndom91 , please pull the code again and try to reinstall requirements, there is a PR for fix in #18 !
And no, you don't need to have an older version of python.

**Comment by ndom91** [comment]
Looks good thanks
