### ISSUE TITLE
User and Password

### ISSUE THREAD

**Issue by thefirstintruder** [Sanix-Darker/Brute-Force-Login#3]
Hi there, 

Using the Heroku live app for security educational purposes, so I'd be grateful if you could tell me the working username and password haha!

Thanks

**Comment by Sanix-Darker** [comment]
Lol lol, sure sure @thefirstintruder , my bad:
Username : sanix
Password : .bleach1234
Link : http://grabme.herokuapp.com/target/

PS: on the password, don't forget the "." before b of bleach
