### ISSUE TITLE
Connexion failed : 404 Not Found (Verify your url)

### ISSUE THREAD

**Issue by SyedOmarNoor** [Sanix-Darker/Brute-Force-Login#4]
I tried to use this for https://www.roblox.com/login, but this error came up.
Other websites work.
setup:
python 3.7
windows 7 ultimate x86-64
requests installed through pip

**Comment by Sanix-Darker** [comment]
Have you followed well all the README installation ?

**Comment by Sanix-Darker** [comment]
if there is an update here, let me know, i will close this issue for now!

**Comment by SyedOmarNoor** [comment]
Here's the console log:

# -------------------------------------------
# | __ )|  ___| |    
# |  _ \| |_  | |    
# | |_) |  _| | |___ 
# |____/|_|   |_____| v1.0.0
# => Brute Force Login <=                     #
# By S4n1x D4rk3r                             #
# #############################################
[+] After inspecting the LOGIN form of your target website, please fill here :

[+] Enter the 'action' attribute on the Login form of the target URL :https://www.roblox.com/Login

[+] Enter the User Field:form-group username-form-group

[+] Enter the Password field:form-group password-form-group
[+] Connecting to: https://www.roblox.com/Login......

[+] {'form-group username-form-group': 'test', 'form-group password-form-group': 'password'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': '123456'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': '12345678'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': '1234'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': 'qwerty'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': '12345'}
[+] Connexion failed : 404 Not Found (Verify your url)
[+] {'form-group username-form-group': 'test', 'form-group password-form-group': 'dragon'}
[+] Connexion failed : Trying again ....
(this is the end of the log)

I'm not sure what to input when it says to input the username and password field.

**Comment by Sanix-Darker** [comment]
You're not entering rights values, i will provide new specifications on what to take exactly

**Comment by Sanix-Darker** [comment]
Done! Please check the last release !

**Comment by Kali95739** [comment]
When are the values I'm having the same problem??

**Comment by SyedOmarNooredu** [comment]
The values are 'username' and 'password' for the username and password (the 'name' attributes).
