### ISSUE TITLE
Syntax error when entering Target Url

### ISSUE THREAD

**Issue by davidk25** [Sanix-Darker/Brute-Force-Login#6]
Hello,

Whenever i try to manually specify "target url" i get syntax error. 
---------------------------------------------------------------------------------------------------------------------------

[+] Select a mode for detecting fields:
[+] 1-) Automatic mode (Will get all necessary field and proceed)
[+] 2-) Manual mode (you will provide necessary informations before continue)
[+] -
[+] 0-) Stop the program
[+] Choice: 2
[+] Manual mode selected 
[+] After inspecting the LOGIN <form />, please fill here :

[+] Enter the target URL (it's the 'action' attribute on the Login form):https://www.facebook.com/login
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    checkpoint_1()
  File "main.py", line 98, in checkpoint_1
    automaticMode()
  File "main.py", line 82, in automaticMode
    checkpoint_1()
  File "main.py", line 100, in checkpoint_1
    manualMode()
  File "main.py", line 20, in manualMode
    url = input("\n[+] Enter the target URL (it's the 'action' attribute on the Login form):")
  File "<string>", line 1
    https://www.facebook.com/login
         ^
SyntaxError: invalid syntax
-----------------------------------------------------------------------------------------------------------------------

I am really stuck at this point, and i have no idea what to do, it does the same with any login url. So any help would be greatly appreciated
Edit: im using kali linux with tor and newest python installed

**Comment by Sanix-Darker** [comment]
LMAO, facebook is on another level dude, you can not fully deal with it using BFL, they use some intelligents blackList modules !
Btw, it's looks like you have updated your message, i saw the url was https://www.roblox.com/login in my mail.

i hope you have the right on using this penTesting tool against this webSite, like i said in my README, am not responsible of usage of it !
By the way, the script is not suppose to crash, on my side i had any error:

![even](https://user-images.githubusercontent.com/22576758/68520224-2fe35900-0296-11ea-9e00-e30b9e3c2317.png)

However, i noticed the real URL to the api is not what you provided but `https://auth.roblox.com/v2/login`, as you can see in this picture i just inspected Network with my chrome browser when i click on login button.
![roblox](https://user-images.githubusercontent.com/22576758/68520163-dd09a180-0295-11ea-87bd-fdac841f86c3.png)

By the way for your error, am sure you added some updates to my code and i don't understand well the end of the Traceback `File "", line 1`, if you really want help, please share evereything thanks.

**Comment by Sanix-Darker** [comment]
Closing for no other replies !
