### ISSUE TITLE
Request Method not working

### ISSUE THREAD

**Issue by DarkStone144** [Sanix-Darker/Brute-Force-Login#9]
How to change the request method to $_POST instead of $_REQUEST

**Comment by Sanix-Darker** [comment]
What do you mean by changing from $_REQUEST to $_POST ? it's not even PHP...

What is done here in python is `requests.post()`, maybe i don't understand well what you are talking about, can you provide more details please ?

**Comment by DarkStone144** [comment]
its my fault whoops
